import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/Header";
import { useRouter } from "next/router";
import ReduxProvider from "./utils/store/ReduxProvider";
import { AuthContextProvider } from "./utils/contexts/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Netflix GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <AuthContextProvider>
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </AuthContextProvider>
      </ReduxProvider>
    </html>
  );
}
